### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Some small fixes, let me know if any of the individual commit messages are not explanatory enough!

One thought, is it ever desirable to not subtract the mean form the stimulus? having a non-zero mean in a stimulus will also lead to a DC offset in the predictions, so it should always increase the error, no?

### CODE REVIEW

**Comment by proloyd** [comment]
The reason why is this scaling=False exists, if suppose you are supplying already scaled stim variables. Then there is not point in scaling it again. This might be useful when you want to try some other way of scaling the stim. Does that make sense?

**Comment by proloyd** [comment]
Thanks for the fixes!

**Comment by christianbrodbeck** [comment]
I was not questioning the usefulness of the `scaling=False`, was only wondering whether you'd ever want to use `baseline=None`? I.e. would you want to subtract the mean even when `scaling=False`?

**Comment by proloyd** [comment]
Not always. Consider a train of impulses, sometimes you may like to fit
this train directly, without subtracting its mean.

**Comment by christianbrodbeck** [comment]
Even for impulses, nonzero mean just adds a DC component to the prediction which should always make the model worse, no?

**Pull request merged**
